### ISSUE TITLE
For 	"1.0.2" in manifest lay "1.0.1"

### ISSUE THREAD

**Issue by sokrata** [homu-konamilk/obsidian-custom-new-file-name#1]
in manifest.json file wrong lay 	"version": "1.0.1". 

For this reason, updating the plugin through the program is incorrect (the plugin says that there is a new version, but clicking Update says that it is not updated)

**Comment by hokolamp** [comment]
Thanks for letting us know. The issue has been fixed. Please update the plugin to the latest version.
